// Events
const NAMESPACES_LIST = "NS_LIST";
const NAMESPACE_LOAD_ROOMS = "NS_LD_RMS";
const JOIN_ROOM = "JOIN_RM";
const NEW_MESSAGE_TO_SERVER = "NEW_MSG_TO_SERVER";
const MESSAGE_TO_CLIENTS = "MSG_TO_CLIENTS";
const LOAD_ROOM_HISTORY = "LD_RM_HIS";
const UPDATE_MEMBERS = "UPD_MEMS";

module.exports = {
  NAMESPACES_LIST,
  NAMESPACE_LOAD_ROOMS,
  JOIN_ROOM,
  NEW_MESSAGE_TO_SERVER,
  MESSAGE_TO_CLIENTS,
  LOAD_ROOM_HISTORY,
  UPDATE_MEMBERS,
};
